export const HeaderLinks = [
    {
        name:"Inicio",
        link:"/"
    },
    {
        name:"Nosotros",
        link:"/us"
    },
    {
        name:"Actividades",
        link:"/activities"
    },
    {
        name:"Novedades",
        link:"/news"
    },
    {
        name:"Testimonios",
        link:"/testimonial"
    },
    {
        name:"Contacto",
        link:"/contact"
    },
    {
        name:"Contribuye",
        link:"/donate"
    }
]